### ISSUE TITLE
occured erro when catkin build smug_planner_ros

### ISSUE THREAD

**Issue by out1Man** [leggedrobotics/smug_planner#1]
when catkin build smug_planner_ros, errors are reported:

**Errors     << smug_planner_msgs:cmake /home/outman/smug_ws/logs/smug_planner_msgs/build.cmake.005.log**
CMake **Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "navigation_msgs"**
  with any of the following names:

    navigation_msgsConfig.cmake
    navigation_msgs-config.cmake

  Add the installation prefix of "navigation_msgs" to CMAKE_PREFIX_PATH or
  set "navigation_msgs_DIR" to a directory containing one of the above files.
  If "navigation_msgs" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

cd /home/outman/smug_ws/build/smug_planner_msgs; catkin build --get-env smug_planner_msgs | catkin env -si  /usr/bin/cmake /home/outman/smug_ws/src/smug_planner/smug_planner_msgs --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/outman/smug_ws/devel/.private/smug_planner_msgs -DCMAKE_INSTALL_PREFIX=/home/outman/smug_ws/install; cd -

...............................................................................
Failed     << smug_planner_msgs:cmake             [ Exited with code 1 ]       
Failed    <<< smug_planner_msgs                   [ 0.4 seconds ]              
Abandoned <<< minkindr                            [ Unrelated job failed ]     
Abandoned <<< minkindr_conversions                [ Unrelated job failed ]     
Abandoned <<< voxblox                             [ Unrelated job failed ]     
Abandoned <<< smug_planner                        [ Unrelated job failed ]     
Abandoned <<< voxblox_ros                         [ Unrelated job failed ]     
Abandoned <<< smug_planner_ros                    [ Unrelated job failed ]     
Finished  <<< eigen_checks                        [ 0.1 seconds ]              
[build] Summary: 6 of 13 packages succeeded.                                   
[build]   Ignored:   2 packages were skipped or are skiplisted.                
[build]   Warnings:  None.                                                     
[build]   Abandoned: 6 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.5 seconds total.

can you tell me how to solve this?
computer version: ubuntu20.04, ros-noetic
Thanks!

**Comment by felix-ch** [comment]
Hi, this was due to a redundant dependency, now it is removed and the issue should be resolved.

**Comment by out1Man** [comment]
thanks!

**Comment by out1Man** [comment]
> Hi, this was due to a redundant dependency, now it is removed and the issue should be resolved.

thanks!
