### ISSUE TITLE
occured erro when catkin build smug_planner_ros

### ISSUE THREAD

**Issue by out1Man** [leggedrobotics/smug_planner#2]
when catkin build smug_planner_ros, errors are reported:

![2023-07-03 11-41-07 的屏幕截图](https://github.com/leggedrobotics/smug_planner/assets/88752313/05f92457-6be8-4be2-a656-6a34355783fe)
![2023-07-03 11-41-18 的屏幕截图](https://github.com/leggedrobotics/smug_planner/assets/88752313/b7953dec-52cf-443a-9dca-5b6b074959cc)

When build the grpc, there is a timeout issue.
Does this mean I need to install gRPC? If so, where should I install it?
Thanks!

**Comment by felix-ch** [comment]
It seems like the gRPC is built along with the protobuf_catkin, and you are not using the required branch of voxblox. The required branch does not install protobuf_catkin (master branch does), and its voxblox_ros does not depend on voxblox_rviz_plugin (master branch does). Please make a new smug_ws from scratch and follow the instructions in the readme to install the required protobuf version and use the required version of voxblox.

**Comment by qingchen-bi** [comment]
grid_map_msgs/GridMap.h: 没有那个文件或目录
   14 | #include <grid_map_msgs/GridMap.h>
请问这是什么错误呢，怎么解决呢，谢谢

**Comment by qingchen-bi** [comment]
> grid_map_msgs/GridMap.h: 没有那个文件或目录 14 | #include <grid_map_msgs/GridMap.h> 请问这是什么错误呢，怎么解决呢，谢谢

已经解决了：
sudo apt-get install ros-noetic-grid-map
