### ISSUE TITLE
Question about traversability map generation

### ISSUE THREAD

**Issue by yansong-ai** [leggedrobotics/smug_planner#3]
Could you please tell me how did you realize the traversability map generation, is the model of "Locomotion Policy Guided Traversability Learning using Volumetric Representations of Complex Environments" open source? ;-)

**Comment by felix-ch** [comment]
The traversability map generation follows the paper "Locomotion Policy Guided Traversability Learning using Volumetric Representations of Complex Environments". There is currently no plan on making the model open-source, sorry.

**Comment by yansong-ai** [comment]
Thanks:-)
